### ISSUE TITLE
Doc generation integration

### ISSUE THREAD

**Issue by luistrigueiros** [google/protobuf-gradle-plugin#110]
The plugin is awesome I love it, it would be nice if it would also generate the documentation from the proto file based for example in proto-gen-doc.

Thanks, 
 Luis Oscar

**Comment by ejona86** [comment]
`protoc-gen-doc` should work fine today with this gradle plugin. Simply specify a protoc plugin, like is done for [`grpc` in the readme](https://github.com/google/protobuf-gradle-plugin#locate-external-executables). Since `protoc-gen-doc` doesn't appear on Maven Central, you will need to specify a `path` instead of an `artifact`.

**Comment by luistrigueiros** [comment]
Could you point me to an example that does this. Thank you.

**Comment by zhangkun83** [comment]
You probably have figured out the solution. FWIW, here is an example:

```gradle
protobuf {
  ...
  // Configure the protoc executable
  protoc {
    // Download from repositories
    artifact = 'com.google.protobuf:protoc:3.0.0'
  }
  // Configure the codegen plugins
  plugins {
    // Define a plugin with name 'doc' and locate its executable
    doc {
      path = '/path/to/protoc-gen-doc'
    }
  }
  generateProtoTasks {
    all().each { task ->
      task.plugins {
        doc {}
      }
    }
  }
}
