### ISSUE TITLE
Tests failed when generate jacoco report

### ISSUE THREAD

**Issue by BulatMukhutdinov** [google/protobuf-gradle-plugin#134]
Hi!
When run tests as usual everything is OK. But when run jacoco test coverage report in methods that use grpc generated classed I have an exception
java.lang.NoClassDefFoundError: Could not initialize class api.Api$GetBalanceRequest

How can I fix it?

**Comment by zhangkun83** [comment]
If you could share your project, or a minimal project that can reproduce this issue, it could help our investigation.

**Comment by ejona86** [comment]
In grpc-java we do use the protobuf plugin and the jacoco plugin at the same time and haven't seen any issue. So the project would be very helpful.

**Comment by BulatMukhutdinov** [comment]
Here is the example. When just run the tests - everything is ok.
But if try gradlew jacoco - it fails with 
java.lang.NoSuchMethodError: api.Api$IsUniqueUsernameRequest.makeImmutable()V

**Comment by ejona86** [comment]
@BulatMukhutdinov, that error is really interesting, because it seems a classpath problem unrelated to the code generator. Also, the jacoco task isn't failing; it is testDebugUnitTest that is failing. The top of the stack trace is important:
```
java.lang.NoSuchMethodError: api.Api$IsUniqueUsernameRequest.makeImmutable()V
	at api.Api$IsUniqueUsernameRequest.<clinit>(Api.java:309)
```

That shows that the generated code (which contains `api.Api$IsUniqueUsernameRequest.<clinit>`) was found. The `makeImmutable()` method is an inherited protected method provided by protobuf-lite. This likely means you are accidentally include a dependency on full protobuf.

Searching for `com.google.protobuf:protobuf-java` in `../gradlew dependencies` shows that a transitive robolectric dependency is bringing in the conflicting protobuf. It seems you are hitting robolectric/robolectric#2643

```
|    +--- org.robolectric:shadows-core:3.3.2
|    |    +--- ...
|    |    \--- com.google.android.apps.common.testing.accessibility.framework:accessibility-test-framework:2.1
|    |         +--- ...
|    |         \--- com.google.protobuf:protobuf-java:2.6.1
```

**Comment by BulatMukhutdinov** [comment]
Thank you! That was a cause of my problem. I just excluded protobuf from robolectric and it works
