### ISSUE TITLE
Error:(4, 0) Cause: com/google/protobuf/gradle/ProtobufPlugin : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by caxton** [google/protobuf-gradle-plugin#22]
Environment:

Android Studio: 1.2.2
Gradle version: 2.2.1
Android plugin version: 1.1.0
jdk version: java-7-openjdk-amd64

build.gradle:

apply plugin: 'com.android.application'
apply plugin: 'com.google.protobuf'

buildscript {
    repositories {
        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
        jcenter()
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.5.0-SNAPSHOT'
    }
}

**Comment by zhangkun83** [comment]
It must be because the artifact was compiled with Java 8 without a target compatibility option. I need to add a ``targetCompatibility = 1.6`` so that future releases support down to JDK6.

That said, none of the released versions support Android, so you will have to build and install the [0.5.x dev branch](https://github.com/google/protobuf-gradle-plugin/tree/v0.5.x) locally to get Android support.
