### ISSUE TITLE
Cannot compile many messages with same name

### ISSUE THREAD

**Issue by jcornaz** [google/protobuf-gradle-plugin#306]
Please consider the following proto files:

`Request.proto`
```proto
option java_outer_classname = "Request"

message Foo {
}
```

`Response.proto`
```proto
option java_outer_classname = "Response"

message Foo {
}
```

Running `./gradlew generateProto` returns the following error:

```
Response.proto:3:9: "Foo" is already defined in file "Request.proto".
```

But:
1. We encounter this issue in the context of migrating from maven to gradle and It worked fine using maven.
2. It should not be a problem, because the two messages have different outer-class names.

**Comment by ejona86** [comment]
Assuming the protobuf package is the same, then the messages have the same protobuf name. So it is definitely a problem.

The maven plugin may have built each file as a separate invocation to `protoc`, which wouldn't have noticed. The gradle plugin uses a single invocation of `protoc`, which has advantages and isn't something I expect to change (but others may feel differently).

If you generated these are two separate projects, then it would probably be fine.

**Comment by jcornaz** [comment]
>Assuming the protobuf package is the same, then the messages have the same protobuf name. So it is definitely a problem.

Why?

Let's assume the package is `com.mycompany.mysoftware`. Then I expect the following generated message classes:
* `com.mycompany.mysoftware.Request.Foo`
* `com.mycompany.mysoftware.Response.Foo`

Where is the problem exactly?

>If you generated these are two separate projects, then it would probably be fine.

That's not an option. I gave my example with two files, but in practice we have dozen of them.

**Comment by ejona86** [comment]
Protobuf needs to be able to refer to the messages. That is done by name. The name is proto package + message name, potentially with nesting.

The appropriate way to do what you want is to use nested messages (or simply use different names):
```
message Request {
  message Foo {}
}
```

**Comment by jcornaz** [comment]
Sorry, but I still don't understand. What is the outerclass used for?

**Comment by ejona86** [comment]
As far as I'm concerned, nobody uses outerclass for Java any more and the only reason it is the default is changing it would break existing users (like, those from a "decade ago" inside of Google). Virtually all protos I see that are used in Java have java_multiple_files.

Now, people still specify java_outer_classname, because the file will still be generated containing reflection information. But the default name is prone to clashing with messages (again, something that can't be changed because of backward compatibility). So the classname used is the proto's file name turned into a class name, like request.proto would become RequestProto (so they all end with Proto).

While the approach you used worked before in Java, it would have broken in most other languages. So in no way is that a proto "feature." It's more of an abuse of a feature that simply hadn't bitten you yet.

Protobuf expects messages to be namespaced, just like is necessary in every other language. Two messages cannot have the same name. You might get lucky (like you did), but it's just waiting to explode in your face (like it did).

**Comment by jcornaz** [comment]
>While the approach you used worked before in Java, it would have broken in most other languages. So in no way is that a proto "feature." It's more of an abuse of a feature that simply hadn't bitten you yet.

Ok, that I understand, and it makes sense.

Thanks for the explanation.
