### ISSUE TITLE
Unable to find google/protobuf/descriptor.proto

### ISSUE THREAD

**Issue by TheRealJagwire** [google/protobuf-gradle-plugin#326]
I'm having trouble compiling a set of proto files, seeing the error: Import "google/protobuf/descriptor.proto" was not found or had errors.

My build file is as follows:

```groovy
buildscript {
    repositories {
        mavenCentral()
   }
   dependencies {
       classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.10'
   }
}

plugins {
    id "com.google.protobuf" version "0.8.10"
    id "java"
}

repositories {
    mavenCentral()
}

sourceSets {
    main {
        proto {
             srcDir '../common'
        }
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.9.0"
    }
    generateProtoTasks {
        generateProto.outputs.dir "my_generated"
        genertaeProto.builtins {
            csharp { }
            remove java
        }
    }
}
```

**Comment by ejona86** [comment]
@zhangkun83, note that they are using csharp. I don't remember if we've considered well-known protos for other languages.

**Comment by zhangkun83** [comment]
@TheRealJagwire can you try adding:
```gradle
dependencies {
  protobuf 'com.google.protobuf:protobuf-java:3.9.0'
}
```

**Comment by TheRealJagwire** [comment]
Adding that block yields the same error message.

**Comment by zhangkun83** [comment]
Yes please.

**Comment by JonasVautherin** [comment]
Just for the record: I am using gRPC, depending on it with:

```gradle
dependencies {
    implementation "io.grpc:grpc-protobuf-lite:${grpcVersion}"

    ...
}
```

I extended `descriptor.proto`, and it seems like I needed the "full" protobuf for that. @zhangkun83's solution above worked, but seemed a bit weird to me because I usually depend on `grpc-protobuf`. So the following worked:

```gradle
dependencies {
    protobuf "io.grpc:grpc-protobuf:${grpcVersion}"

    implementation "io.grpc:grpc-protobuf-lite:${grpcVersion}"

    ...
}
```

Not sure if that's correct, but it seems to say "use the 'full' protobuf for the proto plugin, and then use the 'lite' version when compiling the generated code".
