### ISSUE TITLE
Unable to use linux executable as plugin without extension, due to default extension being 'exe'.

### ISSUE THREAD

**Issue by davidjlynn** [google/protobuf-gradle-plugin#329]
Hi all,

I am trying to use an executable as a plugin which is imported via artifact.
Helpfully there is a osdetector so the correct binary can be selected for windows/linux.

However the default extension that is provided is 'exe'.
[ToolsLocator.groovy](https://github.com/google/protobuf-gradle-plugin/blob/74997dceac6eef0095826067a32f24f11b2c051d/src/main/groovy/com/google/protobuf/gradle/ToolsLocator.groovy#L102)
```groovy
    Map<String, String> notation = [
            group:groupId,
            name:artifact,
            version:version,
            classifier:classifier ?: project.osdetector.classifier,
            ext:extension ?: 'exe',
    ]
```
Linux executables commonly don't have extensions, so when trying to load an artifact with no extension, this always gets defaulted to exe, hence the fetching fails on linux.
For example, this in a build script will still result in exe:
```groovy
ext {
    architecture = project.osdetector.classifier
    executableExtension = architecture == "windows-x86_64" ? "exe": ""
}
protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.9.1'
    }
    plugins {
        doc {
            artifact = "com.company:useful-library:0.1.0:$architecture@$executableExtension"
        }
    }
}
```

Workarounds to this issue:
- Require that artifactory executables have 'exe' extensions
  - This doesn't seem ideal as they aren't windows executables.
- Use the 'elf' extension for linux executables.
  - This seems better, however use of elf is quite often rare.

However both of these options require the artifactory images to be in a certain format, there is no way for someone wishing to use a linux executable, from a repository out of their control, when there is no extension on the linux executable.

How would you feel about removing the default extension, so:
```groovy
    Map<String, String> notation = [
            group:groupId,
            name:artifact,
            version:version,
            classifier:classifier ?: project.osdetector.classifier,
            ext:extension ?: null,
    ]
```

**Comment by zhangkun83** [comment]
The `exe` extension, although seemingly out of place on Linux, isn't causing any problem. I don't remember if the repository actually supported artifacts without extension, but files without extensions is rare (except for Linux executable), and also rare for files downloaded from network. That's why we publish `protoc` executables as `exe`.

I do understand that if you are using an artifact uploaded by someone else, and they don't add extensions, you are unable to use it from the protobuf plugin. The problem seems to be that Groovy's `tokenize()` doesn't produce empty strings, so the tokenization of `'artifact@'` is the same as `'artifact'`, while we would desire different results. This should be an easy fix.

**Comment by voidzcy** [comment]
@davidjlynn 
We would make changes to handle cases when the artifact does not have an explicit extension:
- For artifacts ending with `@`, we will just use `''` as the extension.
- For artifacts without the tail `@`, we will default to `exe`.

So for your case, you would need to conform to something like `com.github.pseudomuto:protoc-gen-doc:1.3.0:linux-x86_64@`
