### ISSUE TITLE
v0.8.11 was released and contains breaking changes

### ISSUE THREAD

**Issue by rpalcolea** [google/protobuf-gradle-plugin#368]
Hi!

0.8.11 was released with https://github.com/google/protobuf-gradle-plugin/commit/9204107e693066bf83b02e0934bf1adb0c090607 which makes Gradle 5.6 a requirement.

This should be considered a breaking change and not a patch release.

Any chance there could be a `0.8.12` with the content of `0.8.10` and make this breaking change `0.9.0`?

Thanks!

**Comment by ejona86** [comment]
I don't think it needs to be a major release, but it probably would have been good to be a minor release. Including a change that big in a patch release is surprising, since it seems we were supporting Gradle 3 previously. (Although the change was done as part of a bug-fix.)

I guess we could potentially use reflection to avoid the Gradle version bump, but it seems there was going to be a requirement on Gradle 5.0 anyway? (Unclear what caused that.)

**Comment by zhangkun83** [comment]
I have been bumping minor versions only for behavioral changes. Gradle version requirements have been raised within patch versions because they were almost always part of bug fixes ([0.8.8](https://github.com/google/protobuf-gradle-plugin/releases/tag/v0.8.8), [0.7.6](https://github.com/google/protobuf-gradle-plugin/releases/tag/v0.7.6)). They should probably have been minor version bumps. We could put this in writing in the upcoming `RELEASING.md`.

**Comment by ejona86** [comment]
The v0.8.8 release didn't seem like a big deal, because v3.0 was over two years old. But I see v0.7.6 was released ~same day as 2.12.

Minor version bumps would probably make it more clear to users in the future.

**Comment by rpalcolea** [comment]
Hi folks, thanks for looking into this. It seems like using APIs only available for the last minor of a major release in gradle is a good candidate for a minor release here. I don't know if reflection is the right solution for this as it just adds more to maintain in future releases. But cutting a new minor and then share with people that you will only get the nice new features starting with 0.9.0 and Gradle 6 for example, it would be totally understandable.

Also, looking at javadocs:

https://docs.gradle.org/5.6/javadoc/org/gradle/api/attributes/LibraryElements.html
https://docs.gradle.org/current/javadoc/org/gradle/api/attributes/LibraryElements.html

Because `LibraryElements` was introduced 5.6, it was incubating. It seems like leveraging it for 0.8.x would mean supporting backwards compatibility as it is incubating and then remove it maybe for 0.9.x


Do you plan on releasing 0.8.10 as 0.8.12? and then do a 0.9.0 with the latest? That would be awesome!

**Comment by voidzcy** [comment]
It's unfortunate, the release had happened. 0.8.11 would be a breaking release. This might shock people who are upgrading, it's unfortunate, I apologize. 😢 

The README on the head has been updated to highlight the Gradle version requirement. At this stage, we are not planing to do a revert release 0.8.12 and then 0.9.0.

**Comment by rpalcolea** [comment]
oh no problem @voidzcy , just wanted to share our findings. Really appreciate your work around this plugin! It is awesome that you leverage new gradle features! I'll close this issue now! thanks everyone for sharing thoughts
