### ISSUE TITLE
how to remove or make sure the test folder that is not generated by the proto task?

### ISSUE THREAD

**Issue by kant111** [google/protobuf-gradle-plugin#379]
Currently, I have the following proto task and it generates everything fine but it also generates a test folder under `generatedFilesBaseDir/test` which is an empty folder. How can I change below code such that the folder `generatedFilesBaseDir/test` is not generated in the first place?
      
```
 protobuf {
            // Configure the protoc executable
            generatedFilesBaseDir = "$rootProject.projectDir/java/src"

            protoc {
                // Download from repositories
                artifact = 'com.google.protobuf:protoc:3.10.0'
            }

            clean {
                delete protobuf.generatedFilesBaseDir
            }

            plugins {
                grpc {
                    artifact = 'io.grpc:protoc-gen-grpc-java:1.23.0'
                }
            }

            generateProtoTasks {
                ofSourceSet('main')*.plugins {
                    // Apply the "grpc" plugin whose spec is defined above, without
                    // options.  Note the braces cannot be omitted, otherwise the
                    // plugin will not be added. This is because of the implicit way
                    // NamedDomainObjectContainer binds the methods.
                    grpc {}
                }
            }
        }
```

**Comment by ejona86** [comment]
I'd suggest not changing `generatedFilesBaseDir` and instead make a `Sync` task that copies the results.

```
task syncGeneratedSources(type: Sync) {
    from "$buildDir/generated/source/proto/main"
    into "$rootProject.projectDir/java/src"
}

protobuf {
    ...
    generateProtoTasks {
        ofSourceSet('main').each { task ->
            task.plugins {
                grpc {}
            }
            syncGeneratedSources.dependsOn task
        }
    }
}

assemble.dependsOn syncGeneratedSources
```

I expect we'll remove `generatedFilesBaseDir` in the future, since it is finicky and manually creating a Sync task produces better results.

**Comment by voidzcy** [comment]
Currently we don't have that option and output directories are [created eagerly](https://github.com/google/protobuf-gradle-plugin/blob/8d421ce224a5f789e118bdd6d919db990751556d/src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy#L487-L490). Since each sourceSet (`main` and `test`) will have a `GenerateProtoTask`, it will create the output directory even if it does not generate anything. This might be improved, or this would not happen if we migrate to use [Gradle task avoidance API](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html) (`generateTestProto` task won't get run if the `test` sourceSet does not have protos, see #304). That would be a quite involved upgrade and we don't foresee that change soon.

Btw, generated code by default locates in `build` directory and it is cleaned up when you do gradle clean and recreated when you rebuild. The empty folder shouldn't bother much, isn't it?

FYI, I don't think
```
clean {
    delete protobuf.generatedFilesBaseDir
}
```
inside the `protobuf` closure in the code snippet above make any sense and you should delete it.
