### ISSUE TITLE
Add .proto files to sourcesJar

### ISSUE THREAD

**Issue by qiyuey** [google/protobuf-gradle-plugin#398]
the two ways now:
```
sourceSets {
    main {
        java.srcDir("build/generated/source/proto/main/grpc")
        java.srcDir("build/generated/source/proto/main/grpckt")
        java.srcDir("build/generated/source/proto/main/java")
        proto.srcDir("../../proto")
    }
}

val sourcesJar by tasks.creating(Jar::class) {
    group = JavaBasePlugin.DOCUMENTATION_GROUP
    archiveClassifier.set("sources")
    from(sourceSets["main"].allSource, sourceSets["main"].proto)
}

publishing {
    publications {
        create<MavenPublication>("default") {
            from(components["java"])
            artifact(sourcesJar)
        }
    }
}
```
or
```
sourceSets {
    main {
        java.srcDir("build/generated/source/proto/main/grpc")
        java.srcDir("build/generated/source/proto/main/grpckt")
        java.srcDir("build/generated/source/proto/main/java")
        java.srcDir("../../proto")
        proto.srcDir("../../proto")
    }
}

java {
    withSourcesJar()
}
```
I hope we can read proto files from sourcesJar which generated without so much kts code.

**Comment by voidzcy** [comment]
Protos are exposed as resources instead of sources. Consumer projects may still want to define their own protos with references to proto types defined in upstream libraries even if they are not depending on the sources variant. It is about exposing proto types as API. The way we package .proto files is to [add them into Jar as resources](https://github.com/google/protobuf-gradle-plugin/blob/8cc58c389855205ee5cae3f2355fd75045520311/src/main/groovy/com/google/protobuf/gradle/ProtobufPlugin.groovy#L260-L267) so that dependent projects are able to include or compile them. https://github.com/google/protobuf-gradle-plugin/issues/390#issuecomment-603833177 proposed a way to not expose protos in generated Jar.
