### ISSUE TITLE
No "proto" extension function for AndroidSourceSet (Gradle Kotlin DSL)

### ISSUE THREAD

**Issue by woohyeok-choi** [google/protobuf-gradle-plugin#429]
Dear whom may it concern,

I try to integrate protobuf-gradle-plugin into Android and Gradle Kotlin DSL.
However, there is no "proto" extension function (which is used to specify a directory containing protobuf files) for AndroidSourceSet, while SourceSet has it, like below (**com.google.protobuf.gradle.ProtobufConfiguratorExts.kt**):

```Kotlin
fun SourceSet.proto(action: SourceDirectorySet.() -> Unit) {
    (this as? ExtensionAware)
        ?.extensions
        ?.getByName("proto")
        ?.let { it as?  SourceDirectorySet }
        ?.apply(action)
}
```

Is there any way to specify the directory for Android and Gradle Kotlin DSL? 
If not, please consider adding "proto" extension function for AndroidSourceSet.

I really appreciate your effort for this excellent plugin :)

Thanks.

**Comment by voidzcy** [comment]
Yes, this seems to be missing for Kotlin DSL and no one has noticed it. Probably because no one has tried to specify custom `proto` source directory set for android using Kotlin DSL.

This fix should be fairly easy, just add an extension for AndroidSourceSet that does the same for Java project's SourceSet. We would need to depend on `com.android.tools.build:gradle`.

Are you interested in sending in a PR for the fix?
