### ISSUE TITLE
Protos files not see another .proto in directory

### ISSUE THREAD

**Issue by Sanysvo** [google/protobuf-gradle-plugin#439]
Hi, I cant normal write .proto files without import. But import syntax have error. I put screenshot for this error. If i write "../proto/usercar.proto" plugin see .proto file but not compile. If write "usercarproto.proto" (this variant on screenshot) plugin not see .proto but right copile
![2020-10-16 22_21_54-Window](https://user-images.githubusercontent.com/54953072/96300738-bd7b0d00-0ffe-11eb-8ea7-b10eb7aaa0b0.jpg)

**Comment by voidzcy** [comment]
Make sure your import clause uses the correct fully qualified (including package name) name for the protos to be imported.

**Comment by Sanysvo** [comment]
My proto files puts in one directory

**Comment by Sanysvo** [comment]
I give you screen. On it you can see that my import is correct

**Comment by Sanysvo** [comment]
If i put proto files in package in com.sanysvo.ptorobufs, genereteProto task is error: files not found

**Comment by Sanysvo** [comment]
Anyone can help me?? The feeling that the plugin just doesn't work correctly. In the import option, you must use the path relative to the src folder. And when generating, the path relative to the file in which the import is called is used. How can I change this?

**Comment by voidzcy** [comment]
What's the package you declared in `usercar.proto`? Assuming it's `com.sanysvo.protos`. Then in `userinfo.proto`, your import clause should be `com/sanysvo/protos/usercar.proto`. See more details on [protobuf document](https://developers.google.com/protocol-buffers/docs/proto#packages).

**Comment by voidzcy** [comment]
I believe this really is caused by [intellij-protobuf-editor plugin](https://github.com/jvolkman/intellij-protobuf-editor). Its auto-configure isn't always working perfectly, it provides option to [manually set the path](https://github.com/jvolkman/intellij-protobuf-editor#path-settings). There is a [similar question on StackOverflow](https://stackoverflow.com/questions/62837953/protocol-buffer-imports-not-recognized-in-intellij).

**Comment by CrispBull** [comment]
I am having similar issue too. It's weird because Android added Datastore to their Jetpack API's but I haven't seen a project that successfully used this proto buffer with the data store and is able to successful handle imports, I think I read somewhere that it's impossible to use import in java projects. This means I can't use other google defined types like duration, TimeStamp, etc because they're not supported, which is really annoying

**Comment by voidzcy** [comment]
> I am having similar issue too. It's weird because Android added Datastore to their Jetpack API's but I haven't seen a project that successfully used this proto buffer with the data store and is able to successful handle imports, I think I read somewhere that it's impossible to use import in java projects. This means I can't use other google defined types like duration, TimeStamp, etc because they're not supported, which is really annoying

That doesn't sound to be the same issue. I believe this issue is about the integration with Intellij IDEA. You should still be able to compile, but the IDE is not able to find the reference for you. If you cannot compile, then something else is wrong.

**Comment by ejona86** [comment]
This should not be a problem as long as you add the `idea` plugin to your project. IntelliJ requires directories to already exist, so there's some plumbing to create directories eagerly if the `idea` or `eclipse` plugins are in the build.
