### ISSUE TITLE
android studio set generatedFilesBaseDir = "$projectDir/src/main/java"

### ISSUE THREAD

**Issue by lgengsy** [google/protobuf-gradle-plugin#463]
when i set  generatedFilesBaseDir = "$projectDir/src/main/java"
i got debug and release folder. i just only won;t one .
new result :

**Comment by lgengsy** [comment]
now result is 
src/main/java/debug/xxx.java
src/main/java/release/xxx.java
but i wish is :
src/main/java/xxx.java

How to implement.
this is my setting in gradle 
`ext.alwaysLib = true //虽然apply了cc-settings-2.gradle，但一直作为library编译，否则别的组件依赖此module时会报错,也可以直接用android.library
apply from: rootProject.file('cc-settings-2.gradle')
apply plugin: 'com.google.protobuf'//插件文档 https://github.com/google/protobuf-gradle-plugin，后续详细研究更完善的配置

//后续优化pb的生成方式及项目路径

android {

  sourceSets {
    main {
      proto {
//        srcDir '../../iusns-proto/proto'
        srcDir 'src/main/proto'
        include '**/*.proto'
        include '**/*.protodevel'

      }

      java {
        srcDir 'src/main/java/release'
      }

      jniLibs.srcDirs = ['libs']
      jni.srcDirs = [] //disable automatic ndk-build.百度定位

    }
  }

  //https://github.com/protocolbuffers/protobuf/blob/master/java/lite.md
  protobuf {

    protoc {
      //编译版本
      artifact = 'com.google.protobuf:protoc:3.14.0'
    }

    //编译task
    generateProtoTasks {
      all().each { task ->

        task.builtins {
          remove java
        }

        task.builtins {
          java {
            option "lite"
          }
        }

//        task.generateDescriptorSet = true
//        task.descriptorSetOptions.path = "${projectDir}/build/pb/{$task.sourceSet.name}.dsc"
//        task.descriptorSetOptions.includeSourceInfo = true
//        task.descriptorSetOptions.includeImports = true
      }

      ofBuildType('release')

    }

    generatedFilesBaseDir = "$projectDir/src/main/java"

  }

  buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
  }
}


dependencies {
  api 'com.google.protobuf:protobuf-javalite:3.14.0'
  protobuf files('../../iusns-proto/proto')

}`

**Comment by voidzcy** [comment]
> when i set generatedFilesBaseDir = "$projectDir/src/main/java"
i got debug and release folder.

Code is generated separately for each variant (here `debug(Main)` and `release(Main)`). It needs to be organized in parallel with the `main` source set. But you put both of them into the `main` source set. Since the main source set is shared by builds for all buildType/productFlavor/variant, you will get duplicated class definition error. See [this doc](https://developer.android.com/studio/build#sourcesets) to understand how Android build organizes source code for buildType/flavor/variant.


Also note, it's a bad idea to set `$generatedFilesBaseDir` to mix with your own code (or it's a bad idea to use `$generatedFilesBaseDir` (see #332), unless you really know how it will impact your project). It pollutes your source directory. You should at least point it to somewhere separately (or more safely, use a `Copy` task to copy it over instead of just let the plugin dump it there).
