### ISSUE TITLE
Do I need to add protobuf library explicitly?

### ISSUE THREAD

**Issue by ottmar-zittlau** [google/protobuf-gradle-plugin#500]
Hi,

I try to make the protobuf-plugin work using the following build.gradle.kts file:
```
plugins {
    // Apply the java-library plugin for API and implementation separation.
    'java-library'
    id("com.google.protobuf") version "0.8.16"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    ...
    
//    implementation("com.google.protobuf:protobuf-java:3.17.1")
    implementation("com.google.protobuf:protobuf-gradle-plugin:0.8.16")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}


sourceSets {
    main {
        proto {
            srcDir("../protofiles")
        }
    }
}
```

When I use the protobuf-gradle-plugin as dependency, the compiler tells me, that it doesn't find the google protobuf package. 
I get many errors of type:
`error: package com.google.protobuf does not exist`

When I explicitly add the google library (the commented line above) and remove the gradle pluing from the list of dependencies, it works.

My questions are:
- Is this the way things work or could I somehow make it work by including the plugin only? If this is correct, does it matter, what version of the plugin (here 0.8.16) and protobuf-library (here 3.17.1) I choose?
- Is it possible to specify the version of the plugin only once either in the `dependencies` or the `plugins` section?

Thanks!

**Comment by voidzcy** [comment]
This is a general Gradle question. The top-level `dependencies{ }` block in the buildscript configures the dependencies to be pulled into the classpath of _the project under the build_ (aka, they are your project's dependencies). The protobuf-gradle-plugin is a dependency for _the buildscript_, so it should be in _the buildscript's classpath_. I'd suggest reading [this section](https://docs.gradle.org/current/userguide/tutorial_using_tasks.html#sec:build_script_external_dependencies) in Gradle's documentation for details. By default, Gradle searches the Gradle plugin portal for plugins and gets the latest version. The protobuf-gradle-plugin is published there. That's why things work without specifying the dependency. You could specify a specific plugin version in the `plugins {}` closure when you declare the plugin.

I'd suggest reading the [Gradle user guide](https://docs.gradle.org/current/userguide/tutorial_using_tasks.html) for the basic usages.

**Comment by ottmar-zittlau** [comment]
Thanks a lot.
