### ISSUE TITLE
How can I have Python "*_pb2_grpc.py" auto generated? 

### ISSUE THREAD

**Issue by gillmylady** [google/protobuf-gradle-plugin#541]
Hey team, I've followed https://github.com/google/protobuf-gradle-plugin#default-outputs and see Python "*_pb2.py" files auto generated. But I don't see *_pb2_grpc.py" files. I see that the default grpc generation is for Java. Is there a way that this gradle plugin could enable generation of Python's grpc files? Thanks!

**Comment by ejona86** [comment]
Generically speaking, you are missing the two `plugins` sections (one defining the binary, and one defining which tasks; see 'javalite' in the documentation). However, the gRPC generator for Python isn't available on Maven Central and I don't know how pypi dependencies normally mix with Gradle. If you know where the binary to run is on the local machine, you could use `path` instead of `artifact`.

**Comment by ejona86** [comment]
See also #559
