### ISSUE TITLE
protoc-3.0.0-osx-x86_64.exe": error=86, Bad CPU type in executable on Mac M1

### ISSUE THREAD

**Issue by truebucha** [google/protobuf-gradle-plugin#543]
Hi! Help will be very appreciated.
I have the issue on one of my dev's Mac. The full error is
```
> java.io.IOException: Cannot run program "/Users/aweinzettl/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protoc/3.0.0/31a580cdff228f572e27920c0abcfa71cd3d95e4/protoc-3.0.0-osx-x86_64.exe": error=86, Bad CPU type in executable
```
I believe that Mac must not run *.exe files. Because it is windows executable.
Mac can run binary files with no extension like protoc-3.0.0-osx-x86_64.

Please provide a glue - 
* is protoc-3.0.0-osx-x86_64.exe is the binary that required to be run, and I should remove the extension
* or it is artefact and I should find out a way to remove the step that runs protoc-3.0.0-osx-x86_64 from gradle

I am not very common with the potoc for Android. The issues is very rare because for other devs all fine.

Thank you in advance!

**Comment by ejona86** [comment]
Run `file` on the binary to see that it isn't a Windows executable. Maven Central requires artifacts to have an extension, so `exe` was chosen; it could have been `bin` just as easily.

This issue is unrelated to the gradle plugin. https://github.com/protocolbuffers/protobuf would be the more appropriate location.

Look again at the title: x86_64, Mac M1, Bad CPU type. The problem is trying to run a x86_64 binary on the ARM M1. Newer builds of protobuf have "aarch_64" versions, but they are actually just copies of the x86_64 binaries. See https://github.com/protocolbuffers/protobuf/pull/8557 . To my knowledge, there aren't yet actual ARM builds of protoc available yet, but you can use the current builds with Rosetta without much problem.

**Comment by truebucha** [comment]
@ejona86 Thank you very much!

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.

**Comment by truebucha** [comment]
The root cause: **There was no Rosetta installed on the Mac**. It leads to that strange errors.

How to fix: To install Rosetta use Terminal app 
``` softwareupdate --install-rosetta --agree-to-license ```
