### ISSUE TITLE
0.8.18 shipping 3 CVE vulnerabilities (CVE-2021-29425, CVE-2020-8908, CVE-2020-15250)

### ISSUE THREAD

**Issue by mvniekerk** [google/protobuf-gradle-plugin#545]
From:
https://mvnrepository.com/artifact/com.google.protobuf/protobuf-gradle-plugin/0.8.18

Guava, commons-io and junit needs a version bump.

**Comment by ejona86** [comment]
Commons-io and junit are only used during testing. They don't impact users and aren't interesting.

The Guava vulnerability does not impact this software. And upgrading Guava doesn't really fix anything; it seems the problematic method was just marked deprecated. Last I saw, we don't really get to choose the version of Guava being used. There's compatibility issues with Gradle and the Gradle Android plugin. See #345 for a taste. It is probably time to upgrade Guava again, but it isn't as trivial as "bump the version."

But there's no need to panic for anything brought up here. It'd be fair to upgrade all the dependencies "just because." There's three dependencies that actually matter to users: guava, osdetector-gradle-plugin, and commons-lang. osdetector-gradle-plugin and commons-lang appear to be at the latest version we can use.  Gradle master is using Guava 30.1.1-jre, so there may room for an upgrade there. But we'll have to figure out what versions it breaks compatibility with.

**Comment by mvniekerk** [comment]
Thanks @ejona86 -
I'm only using this to generate the code so I agree with the "there's no real problem here" sentiment.
That being said, our enterprise vulnerability scanners (OWASP, Contrast) are screaming at us, giving our project a rubbish security score. In the land of KPI's, pragmatism wins.
I have submitted a PR (https://github.com/google/protobuf-gradle-plugin/pull/546) to this effect.
Thank you again for your consideration.

**Comment by ejona86** [comment]
Wait a minute... Maven Central. We really shouldn't be recommending using Maven Central. In the Gradle Plugins repo, the test scopes aren't included. https://plugins.gradle.org/m2/gradle/plugin/com/google/protobuf/protobuf-gradle-plugin/0.8.9/ . Guava would still need to be addressed.

Looks like we are still using the Maven plugin to publish to Maven Central. We should swap to the maven-publish plugin, and then the test scopes wouldn't be included there as well.

**Comment by mvniekerk** [comment]
Thank you for the updates on this.
Is it possible to publish a new version of the plugin, please?

**Comment by ejona86** [comment]
I think Guava is still a problem, and for that it would be helpful to know what version of Gradle you are using, because we may need to drop support for older Gradle versions.

**Comment by ejona86** [comment]
Also, as I mentioned, you can swap to the Gradle Plugins Portal already and it won't have the commons-io and junit deps.

**Comment by mvniekerk** [comment]
On v7.4 of Gradle.
I've changed to gradle plugin portal, thanks for that.

**Comment by ejona86** [comment]
v0.8.19 is released and included #547, so this is fixed.
