### ISSUE TITLE
Protoc artifact path is not being used

### ISSUE THREAD

**Issue by LiamMayston-MNR** [google/protobuf-gradle-plugin#630]
Hi, I have set the protoc arifact path as so in my app build.gradle but when it builds, it uses a different path as seen by the error.

```
protobuf {
// Configure the protoc executable
    protoc {
        artifact = 'com.google.protobuf:protoc:3.7.0:osx-x86_64'
    }
    plugins {
        javalite {
        // The codegen for lite comes as a separate artifact
            artifact = "com.google.protobuf:protoc-gen-javalite:3.0.0:osx-x86_64"
        }
    }
 }
```

```
Execution failed for task ':barcode_scan:generateDebugProto'.
> Could not resolve all files for configuration ':barcode_scan:protobufToolsLocator_protoc'.
   > Could not find protoc-osx-aarch_64.exe (com.google.protobuf:protoc:3.11.4).
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/protobuf/protoc/3.11.4/protoc-3.11.4-osx-aarch_64.exe
```

How would I go about fixing this?

**Comment by ejona86** [comment]
The error message does not match the snippet. The snippet looks fine. But for the error message, that's because osx-aarch_64 doesn't exist for 3.11.4. You need a newer protoc. Note that for a while the osx-aarch_64 binary is actually a renamed x86_64 binary and intended to be used with Rosetta (to make using this plugin easier). I believe the newest protocs have native aarch64.

**Comment by LiamMayston-MNR** [comment]
Oh I see. It was actually an issue with an outdated package I was using.
But thank you for setting me on the right path.
