### ISSUE TITLE
Support for gradle experimental android plugin

### ISSUE THREAD

**Issue by avf** [google/protobuf-gradle-plugin#85]
Hi!
Is it possible to use this plugin with the [gradle experimental android plugin](http://tools.android.com/tech-docs/new-build-system/gradle-experimental)? Since the experimental plugin requires gradle 2.10, I've tried it with release 0.7.5 of this plugin, but it doesn't seem to work, it says it requires the android plugin. Is there a way to work around this?

**Comment by zhangkun83** [comment]
Probably not possible at this moment, since the experimental Android plugin uses Gradle's new configuration model. There is a stalling PR (#44) for the protobuf plugin to make it use the configuration model. Even if that PR is in, it may still require additional effort to be compatible with the experimental Android plugin.

This issue has been on my radar for a while, I just haven't got time for it. Hopefully I can make some progress in Q3.

**Comment by LouisCAD** [comment]
Isn't this issue obsolete now?

**Comment by zpencer** [comment]
#121 suggests we do have android support now, @zhangkun83 can you confirm that we can close this?

**Comment by syslogic** [comment]
The `README.md` should be updated, because it still reads:

> The experimental Android plugin is not supported yet (#85).
